linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - revive
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - gosec
    - interfacer
    - lll
    - maligned
    - megacheck
    - nakedret
    - scopelint
    - structcheck
    - varcheck
    - whitespace

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - docs
    - vendor
  allow-parallel-runners: true
  go: "1.21"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 