FROM golang:1.24-alpine

WORKDIR /app

# Instalar dependências do sistema
RUN apk add --no-cache git

# Copiar arquivos de módulos e baixar dependências
COPY go.mod go.sum ./
RUN go mod download

# Copiar o código fonte
COPY . .

# Comando para rodar os testes (será sobrescrito pelo docker-compose)
CMD ["go", "test", "-v", "./..."] 