version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/flickly_dev
    depends_on:
      - postgres
    networks:
      - flickly-network
    volumes:
      - .:/app  # Para desenvolvimento, permitindo hot reload

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flickly_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flickly-network

networks:
  flickly-network:
    driver: bridge

volumes:
  postgres_data: 