version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    environment:
      - GO_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/flickly_test
    depends_on:
      - postgres
    networks:
      - test-network
    command: go test -v ./internal/integration_tests

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flickly_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  postgres_data: 