// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/flickly/version": {
            "get": {
                "description": "Retorna informações sobre a versão da API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Verificar versão da API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Retorna o status de saúde do servidor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Verificar saúde do servidor",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/mock": {
            "put": {
                "description": "Cria um novo mock com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mockedapi"
                ],
                "summary": "Criar mock",
                "parameters": [
                    {
                        "description": "Dados do mock",
                        "name": "mock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/viewmodel.RouteViewModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.RouteViewModel"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/oauth/register": {
            "post": {
                "description": "Cria uma nova conta de usuário no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Registra um novo usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário para registro",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/viewmodel.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário registrado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Usuário já existe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/oauth/token": {
            "post": {
                "description": "Gera um token de acesso usando OAuth2",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Autentica um usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tipo de concessão (password ou refresh_token)",
                        "name": "grant_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do cliente",
                        "name": "client_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Segredo do cliente",
                        "name": "client_secret",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nome de usuário (email) - obrigatório para grant_type=password",
                        "name": "username",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Senha do usuário - obrigatório para grant_type=password",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Refresh token - obrigatório para grant_type=refresh_token",
                        "name": "refresh_token",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Escopo do token",
                        "name": "scope",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token gerado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Credenciais inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/simplerule/expense": {
            "post": {
                "description": "Cria um novo expense com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simplerule"
                ],
                "summary": "Criar expense",
                "parameters": [
                    {
                        "description": "Dados do expense",
                        "name": "expense",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/viewmodel.PostExpenseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token gerado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.PostExpenseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/simplerule/subcategories": {
            "get": {
                "description": "Lista todas as subcategorias",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simplerule"
                ],
                "summary": "Listar subcategorias",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.ListAllSubcategoriesViewModelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Cria um novo usuário com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Criar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/viewmodel.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/viewmodel.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.User": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_type": {
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "verified_email": {
                    "type": "boolean"
                }
            }
        },
        "viewmodel.ActionViewModel": {
            "type": "object",
            "properties": {
                "condition": {
                    "$ref": "#/definitions/viewmodel.ConditionViewModel"
                },
                "cookieName": {
                    "type": "string"
                },
                "cookieValue": {
                    "type": "string"
                },
                "fieldToSet": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "removeCookie": {
                    "type": "boolean"
                },
                "result": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "viewmodel.BodyViewModel": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                }
            }
        },
        "viewmodel.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "viewmodel.ConditionViewModel": {
            "type": "object",
            "properties": {
                "fieldToCompare": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "valueToCompare": {
                    "type": "string"
                }
            }
        },
        "viewmodel.CookieViewModel": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "expires": {
                    "type": "integer"
                },
                "httpOnly": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "secure": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "viewmodel.CreateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "viewmodel.CreateUserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "viewmodel.HeaderViewModel": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "viewmodel.HttpResponseViewModel": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/viewmodel.BodyViewModel"
                },
                "cookies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.CookieViewModel"
                    }
                },
                "headers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.HeaderViewModel"
                    }
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "viewmodel.ListAllSubcategoriesViewModelResponse": {
            "type": "object",
            "properties": {
                "subcategories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.SubcategoryResponse"
                    }
                }
            }
        },
        "viewmodel.MockViewModel": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.ConditionViewModel"
                    }
                },
                "hasCondition": {
                    "type": "boolean"
                },
                "response": {
                    "$ref": "#/definitions/viewmodel.HttpResponseViewModel"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.RuleViewModel"
                    }
                }
            }
        },
        "viewmodel.PostExpenseRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Valor em centavos para evitar erros de float",
                    "type": "number"
                },
                "commitmentId": {
                    "description": "Refere-se ao Commitment",
                    "type": "string"
                },
                "date": {
                    "description": "Data do lançamento",
                    "type": "string"
                },
                "description": {
                    "description": "Descrição adicional",
                    "type": "string"
                },
                "installmentNumber": {
                    "description": "Controle de parcelas (ex: 6). O 6/12 está no commitment",
                    "type": "integer"
                },
                "isReference": {
                    "description": "Campo \"É apenas referência?\". Utilizado para simular e contabilizar despesas futuras",
                    "type": "boolean"
                },
                "subcategoryId": {
                    "description": "Ex: Shelter, Entertainment (o \"SubType\")",
                    "type": "string"
                }
            }
        },
        "viewmodel.PostExpenseResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "viewmodel.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "viewmodel.RegisterResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/entities.User"
                }
            }
        },
        "viewmodel.RouteViewModel": {
            "type": "object",
            "properties": {
                "methods": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.MockViewModel"
                    }
                },
                "paths": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "viewmodel.RuleViewModel": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/viewmodel.ActionViewModel"
                    }
                },
                "priority": {
                    "type": "integer"
                }
            }
        },
        "viewmodel.SubcategoryResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/viewmodel.CategoryResponse"
                },
                "categoryId": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "viewmodel.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "scope": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string"
                }
            }
        },
        "github_com_rkaturabara_flickly_internal_domain_users_entities.User": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_type": {
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "verified_email": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Flickly API",
	Description:      "API do projeto Flickly",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
